server {
    listen 80;
    listen [::]:80;

    root /usr/share/nginx/html;
    index index.html;

    # 1. BLOQUE DE PROXY (Regla de la API)
    # Si la ruta comienza con /api/, mándala al Backend.
    location /api/ {
        # CRÍTICO: Aquí usas la IP y puerto de tu Backend. 
        # Asegúrate de que esta URL esté correcta
        proxy_pass http://34.203.25.93:3000/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
    
    
    # 2. BLOQUE GENERAL (Regla del sitio web)
    # Si no es /api/ ni un archivo existente, carga el index.html (para React Router)
    location / {
        try_files $uri $uri/ /index.html;
    }
}