server {
    listen 80;
    listen [::]:80;

    root /usr/share/nginx/html;
    index index.html;

    # Bloque de Proxy Inverso
    location /users/ {
        # CRÍTICO: Aquí usamos la IP real del BACKEND (3.213.85.231)
        # Asegúrate de usar la IP del Backend
        proxy_pass http://3.213.85.231:3000/users/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
    
    # Manejo de Rutas de la SPA (Single Page Application)
    # Cualquier ruta que no sea /users/ o un archivo, la dirige a index.html
    location / {
        try_files $uri $uri/ /index.html;
    }
}